"""add short_name to reports

Revision ID: 8b2f6a00f2ac
Revises: cd33187695a9
Create Date: 2026-08-27 21:01:55.741319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2f6a00f2ac'
down_revision: Union[str, Sequence[str], None] = 'cd33187695a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('short_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'short_name')
    # ### end Alembic commands ###
