"""create_all_tables

Revision ID: cd33187695a9
Revises: 
Create Date: 2026-07-23 23:13:46.066063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd33187695a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('cache_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('inn', sa.String(length=12), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_cache_key'), 'cache', ['cache_key'], unique=True)
    op.create_index('ix_cache_expires', 'cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_cache_id'), 'cache', ['id'], unique=False)
    op.create_index(op.f('ix_cache_inn'), 'cache', ['inn'], unique=False)
    op.create_index('ix_cache_inn_type', 'cache', ['inn', 'cache_type'], unique=False)
    op.create_index('ix_cache_type_key', 'cache', ['cache_type', 'cache_key'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('inn', sa.String(length=12), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('ogrn', sa.String(length=15), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=True),
    sa.Column('html_content', sa.Text(), nullable=False),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('revenue', sa.String(length=50), nullable=True),
    sa.Column('profit', sa.String(length=50), nullable=True),
    sa.Column('assets', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_inn'), 'reports', ['inn'], unique=False)
    op.create_index('ix_reports_status', 'reports', ['status'], unique=False)
    op.create_index('ix_reports_user_created', 'reports', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_user_id'), 'reports', ['user_id'], unique=False)
    op.create_index('ix_reports_user_inn', 'reports', ['user_id', 'inn'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('language_code', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.Column('total_requests', sa.Integer(), nullable=True),
    sa.Column('last_request_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_active', 'users', ['is_active', 'telegram_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index('ix_users_telegram_username', 'users', ['telegram_id', 'username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_telegram_username', table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_users_active', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_reports_user_inn', table_name='reports')
    op.drop_index(op.f('ix_reports_user_id'), table_name='reports')
    op.drop_index('ix_reports_user_created', table_name='reports')
    op.drop_index('ix_reports_status', table_name='reports')
    op.drop_index(op.f('ix_reports_inn'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_cache_type_key', table_name='cache')
    op.drop_index('ix_cache_inn_type', table_name='cache')
    op.drop_index(op.f('ix_cache_inn'), table_name='cache')
    op.drop_index(op.f('ix_cache_id'), table_name='cache')
    op.drop_index('ix_cache_expires', table_name='cache')
    op.drop_index(op.f('ix_cache_cache_key'), table_name='cache')
    op.drop_table('cache')
    # ### end Alembic commands ###
